battery_system:
  batt_replacement_schedule_percent:
    - 0
  batt_bank_replacement:
    - 0
  batt_replacement_option: 0
  batt_computed_bank_capacity: 0
  batt_meter_position: 0
system_costs:
  om_fixed: [0]
  om_production: [0]
  om_capacity: [0]
  om_batt_fixed_cost: 0
  om_batt_variable_cost: [0]
  om_batt_capacity_cost: 0
  om_batt_replacement_cost: 0
  om_replacement_cost_escal: 0
system_use_lifetime_output: 0
financial_parameters:
  inflation_rate: 0.0 # nominal basis
  real_discount_rate: 0.063 # nominal return based on 2024 ATB basline workbook
  federal_tax_rate: 21.0 # https://taxsummaries.pwc.com/quick-charts/corporate-income-tax-cit-rates
  state_tax_rate: 8.84 # https://taxfoundation.org/data/all/state/state-corporate-income-tax-rates-brackets-2024/
  property_tax_rate: 0.71
  insurance_rate: 0.5
  debt_percent: 72.4 # based on 2024 ATB
  term_int_rate: 4.4 # based on 2024 ATB
  months_working_reserve: 1
  analysis_start_year: 2025
  installation_months: 12
  sales_tax_rate_state: 8.50 # average combined state and local sales tax in Arcata, CA
  admin_expense_percent_of_sales: 0.0 # H2FAST default
  capital_gains_tax_rate: 15.0 # H2FAST default
  debt_type: "Revolving debt" # H2FAST default
  depreciation_method: "MACRS"
  depreciation_period: 5 # years - as specified by the IRS MACRS schedule for wind and solar https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
revenue:
  ppa_price_input: [0.0] # cents/kWh
  ppa_escalation: 0 # %
cp_capacity_credit_percent: [0]
degradation: [0]