battery_system:
  batt_replacement_schedule_percent:
    - 0
  batt_bank_replacement:
    - 0
  batt_replacement_option: 0
  batt_computed_bank_capacity: 0
  batt_meter_position: 0
system_costs:
  om_fixed: [0]
  om_production: [0]
  om_capacity: [0]
  om_batt_fixed_cost: 0
  om_batt_variable_cost: [0]
  om_batt_capacity_cost: 0
  om_batt_replacement_cost: 0
  om_replacement_cost_escal: 0
system_use_lifetime_output: 0
financial_parameters:
  inflation_rate: 0.0 # nominal basis
  real_discount_rate: 0.063 # nominal return based on 2024 ATB baseline workbook - with 0% inflation, real and nominal rates are equal
  federal_tax_rate: 21.0 
  state_tax_rate: 9.8
  property_tax_rate: 1.18
  insurance_rate: 0.5
  debt_percent: 72.4 # based on 2024 ATB
  term_int_rate: 4.4 # based on 2024 ATB
  months_working_reserve: 1
  analysis_start_year: 2025
  installation_months: 36
  sales_tax_rate_state: 8.04 # average combined state and local sales tax in MN
  admin_expense_percent_of_sales: 0.0 # H2FAST default
  capital_gains_tax_rate: 15.0 # H2FAST default
  debt_type: "Revolving debt" # H2FAST default
  depreciation_method: "MACRS"
  depreciation_period: 5
cp_capacity_credit_percent: [0]
degradation: [0]
revenue:
  ppa_price_input: [0.0] # cents/kWh
  ppa_escalation: 0 # %
