battery_system:
  batt_replacement_schedule_percent:
    - 0
  batt_bank_replacement:
    - 0
  batt_replacement_option: 0
  batt_computed_bank_capacity: 0
  batt_meter_position: 0
system_costs:
  om_fixed: [0]
  om_production: [0]
  om_capacity: [0]
  om_batt_fixed_cost: 0
  om_batt_variable_cost: [0]
  om_batt_capacity_cost: 0
  om_batt_replacement_cost: 0
  om_replacement_cost_escal: 0
system_use_lifetime_output: 0
financial_parameters:
  inflation_rate: 0.0 # nominal basis
  real_discount_rate: 10.5 # nominal return based on 2024 ATB baseline workbook for fixed-bottom offshore wind nominal and real rates are the same for the nominal analysis case
  federal_tax_rate: 21.0 # https://taxsummaries.pwc.com/quick-charts/corporate-income-tax-cit-rates
  state_tax_rate: 0.75 # https://comptroller.texas.gov/taxes/franchise/ --> The TX franchise tax should be applied to margin but is included in income tax here as an approximation
  property_tax_rate: 1.47 # average effective real property tax rate in Texas https://taxfoundation.org/data/all/state/property-taxes-by-state-county-2024/
  insurance_rate: 0.5
  debt_percent: 73.4 # 2024 ATB uses 73.4% debt for offshore fixed-bottom wind
  term_int_rate: 7.0 # nominal interest rate based on 2024 ATB for fixed-bottom offshore wind
  months_working_reserve: 1
  analysis_start_year: 2025
  installation_months: 12
  sales_tax_rate_state: 8.20 # average combined state and local sales tax in TX
  admin_expense_percent_of_sales: 0.0 # H2FAST default
  capital_gains_tax_rate: 15.0 # H2FAST default
  debt_type: "Revolving debt" # H2FAST default
  depreciation_method: "MACRS"
  depreciation_period: 5
cp_capacity_credit_percent: [0]
degradation: [0]
revenue:
  ppa_price_input: [0.0] # cents/kWh
  ppa_escalation: 0 # %
