battery_system:
  batt_replacement_schedule_percent:
    - 0
  batt_bank_replacement:
    - 0
  batt_replacement_option: 0
  batt_computed_bank_capacity: 0
  batt_meter_position: 0
system_costs:
  om_fixed: [0]
  om_production: [0]
  om_capacity: [0]
  om_batt_fixed_cost: 0
  om_batt_variable_cost: [0]
  om_batt_capacity_cost: 0
  om_batt_replacement_cost: 0
  om_replacement_cost_escal: 0
system_use_lifetime_output: 0
financial_parameters:
  inflation_rate: 0.0 # nominal basis
  real_discount_rate: 6.3 # nominal return based on 2024 ATB baseline workbook for land-based wind. Nominal and real rates are equal with 0% inflation
  federal_tax_rate: 21.0 # https://taxsummaries.pwc.com/quick-charts/corporate-income-tax-cit-rates
  state_tax_rate: 0.75 # https://comptroller.texas.gov/taxes/franchise/ --> The TX franchise tax should be applied to margin but is included in income tax here as an approximation
  property_tax_rate: 1.47 # average effective real property tax rate in Texas https://taxfoundation.org/data/all/state/property-taxes-by-state-county-2024/
  insurance_rate: 1.0 # percent of CAPEX estimated based on https://www.nrel.gov/docs/fy25osti/91775.pdf
  debt_percent: 72.4 # based on 2024 ATB for land-based wind
  term_int_rate: 4.4 # based on 2024 ATB nominal interest rate for land-based onshore wind
  months_working_reserve: 1
  analysis_start_year: 2030
  installation_months: 36
  sales_tax_rate_state: 8.20 # average combined state and local sales tax in TX https://taxfoundation.org/location/texas/
  admin_expense_percent_of_sales: 0.0 # H2FAST default
  capital_gains_tax_rate: 15.0 # H2FAST default
  debt_type: "Revolving debt" # H2FAST default
  depreciation_method: "MACRS"
  depreciation_period: 5 # years - for clean energy facilities as specified by the IRS MACRS schedule https://www.irs.gov/publications/p946#en_US_2020_publink1000107507
cp_capacity_credit_percent: [0]
degradation: [0]
revenue:
  ppa_price_input: [0.0] # cents/kWh
  ppa_escalation: 0 # %
