site: #!include flatirons_site.yaml
  data:
    lat: 32.31714
    lon: -100.18
    elev: 762
    year: 2013
    tz: -6
    site_boundaries: 
      verts:  
        - [0.0, 0.0]
        - [0.0, 20000.0]
        - [20000.0, 20000.0]
        - [20000.0, 0.0] 
      verts_simple: 
        - [0.0, 0.0]
        - [0.0, 20000.0]
        - [20000.0, 20000.0]
        - [20000.0, 0.0]
  solar_resource_file: "../../input-files/weather/solar/32.31714_-100.18_psmv3_60_2013.csv" 
  wind_resource_file: "../../input-files/weather/wind/32.31714_-100.18_windtoolkit_2013_60min_100m_120m.srw"
  wave_resource_file: ""
  grid_resource_file: ""
  hub_height: 115.0
  capacity_hours: []
  solar: true
  wind: true
  wave: false
  wind_resource_origin: "WTK"
technologies:
  wind:
    num_turbines: 175
    turbine_rating_kw: 6000.0
    model_name: floris
    timestep: [0, 8760]
    floris_config: input_files/floris/floris_input_lbw_6MW.yaml
    fin_model: !include default_fin_config.yaml
  pv:
    system_capacity_kw: 750500
    dc_degradation: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    fin_model: !include default_fin_config.yaml
  battery:
    system_capacity_kwh: 375750
    system_capacity_kw: 375750
    minimum_SOC: 20.0
    maximum_SOC: 100.0
    initial_SOC: 90.0
    fin_model: !include default_fin_config.yaml
  grid:
    interconnect_kw: 2000000 # Set higher than rated generation capacity
    fin_model: !include default_fin_config.yaml

config:
  simulation_options:
    wind:
      skip_financial: false
  dispatch_options:
    battery_dispatch: load_following_heuristic # load_following_heuristic #heuristic
    solver: cbc
    n_look_ahead_periods: 48
    grid_charging: false
    pv_charging_only: false
    include_lifecycle_count: false
  cost_info:
    wind_installed_cost_mw: 1380000 # (2022USD) 2025 costs in 2022 USD from NREL 2024 ATB for land-based wind. 2025 used as an overnight-capex lock-in date for 2030 operation
    solar_installed_cost_mw: 1323000 # (2022USD) 2025 costs in 2022 USD from NREL 2024 ATB for utility-scale pv. 2025 used as an overnight-capex lock-in date for 2030 operation
    storage_installed_cost_mwh: 310000 # (2022USD) 2025 battery costs in 2022 USD from NREL 2024 ATB for utility-scale battery storage. 2025 used as an overnight-capex lock-in date for 2030 operation
    storage_installed_cost_mw: 311000 # (2022USD) 2025 battery costs in 2022 USD from NREL 2024 ATB for utility-scale battery storage. 2025 used as an overnight-capex lock-in date for 2030 operation
    wind_om_per_kw: 29 # (2022USD) 2030 costs in 2022 USD from 2024 ATB for land-based wind
    pv_om_per_kw:  18 # (2022USD) 2030 costs in 2022 USD from NREL 2024 ATB for utility-scale PV
    battery_om_per_kw: 15.525 # (2022USD) based on 2.5 percent of battery capex/kW for a 1-hour battery using both power and energy costs above
